[package]
name = "fsk"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
colored = "3.1.1"
env_logger = "0.11.9"
home = "0.5.12"
log = "0.4.29"
walkdir = "2.5.0"
